/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControleProduto;

import ControleDeVendas.ControlaVenda;
import ControleDeVendas.JPanelCarrinhoDeCompras;
import ControleDeVendas.Vendas;
import GerenciamentoDeFuncionarios.Funcionario;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juliano
 */
public class JPanelConsultarProduto extends javax.swing.JPanel {

    /**
     * Creates new form JPanelConsultarProduto
     */
    DefaultTableModel modelo;
    ArrayList<Produto> produtos;
    Produto produto;
    String idVenda;
    Funcionario funcionario;
    

    public JPanelConsultarProduto(Vendas venda, Funcionario func) {
        initComponents();
        
        idVenda = venda.getVendaId();
        funcionario = func;
        
        jInternalFrameAdicionandoAoCarrinho.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConsultarProduto = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jButtonDetalhes = new javax.swing.JButton();
        jLabelNomeProduto = new javax.swing.JLabel();
        jTextFieldCampoPesquisa = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonEditarProduto = new javax.swing.JButton();
        jButtonAdicionarAoCarrinho = new javax.swing.JButton();
        jInternalFrameAdicionandoAoCarrinho = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();

        jPanelConsultarProduto.setMaximumSize(new java.awt.Dimension(995, 595));
        jPanelConsultarProduto.setMinimumSize(new java.awt.Dimension(995, 595));

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID:", "Nome:", "Descrição:", "Preço:", "Estoque:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProdutos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableProdutos);

        jButtonDetalhes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonDetalhes.setText("Detalhes");
        jButtonDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetalhesActionPerformed(evt);
            }
        });

        jLabelNomeProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelNomeProduto.setText("Nome do produto:");

        jTextFieldCampoPesquisa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldCampoPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCampoPesquisaKeyPressed(evt);
            }
        });

        jButtonPesquisar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonEditarProduto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonEditarProduto.setText("Editar");
        jButtonEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarProdutoActionPerformed(evt);
            }
        });

        jButtonAdicionarAoCarrinho.setText("Adicionar ao Carrinho");
        jButtonAdicionarAoCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarAoCarrinhoActionPerformed(evt);
            }
        });

        jInternalFrameAdicionandoAoCarrinho.setTitle("Adicionando ao Carrinho");
        jInternalFrameAdicionandoAoCarrinho.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Adicionar ao Carrinho");

        javax.swing.GroupLayout jInternalFrameAdicionandoAoCarrinhoLayout = new javax.swing.GroupLayout(jInternalFrameAdicionandoAoCarrinho.getContentPane());
        jInternalFrameAdicionandoAoCarrinho.getContentPane().setLayout(jInternalFrameAdicionandoAoCarrinhoLayout);
        jInternalFrameAdicionandoAoCarrinhoLayout.setHorizontalGroup(
            jInternalFrameAdicionandoAoCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameAdicionandoAoCarrinhoLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jInternalFrameAdicionandoAoCarrinhoLayout.setVerticalGroup(
            jInternalFrameAdicionandoAoCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameAdicionandoAoCarrinhoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelConsultarProdutoLayout = new javax.swing.GroupLayout(jPanelConsultarProduto);
        jPanelConsultarProduto.setLayout(jPanelConsultarProdutoLayout);
        jPanelConsultarProdutoLayout.setHorizontalGroup(
            jPanelConsultarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultarProdutoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelConsultarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelConsultarProdutoLayout.createSequentialGroup()
                        .addComponent(jLabelNomeProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelConsultarProdutoLayout.createSequentialGroup()
                        .addComponent(jButtonAdicionarAoCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jButtonEditarProduto)))
                .addGap(18, 18, 18)
                .addGroup(jPanelConsultarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jButtonDetalhes))
                .addGap(27, 27, 27))
            .addGroup(jPanelConsultarProdutoLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jInternalFrameAdicionandoAoCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelConsultarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultarProdutoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );
        jPanelConsultarProdutoLayout.setVerticalGroup(
            jPanelConsultarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultarProdutoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelConsultarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeProduto)
                    .addComponent(jTextFieldCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar))
                .addGap(98, 98, 98)
                .addComponent(jInternalFrameAdicionandoAoCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(jPanelConsultarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDetalhes)
                    .addComponent(jButtonEditarProduto)
                    .addComponent(jButtonAdicionarAoCarrinho))
                .addContainerGap())
            .addGroup(jPanelConsultarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultarProdutoLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(68, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelConsultarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelConsultarProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        //BOTÃO DE PESQUISAR PRODUTOS
        if (jTextFieldCampoPesquisa.getText().equals("Nome do Produto")) {
            JOptionPane.showMessageDialog(null, "Digite um nome para realizar a pesquisa.");
        } else {
            modelo = (DefaultTableModel) jTableProdutos.getModel();
            modelo.setNumRows(0);
            produtos = new ControlaProduto().getListaProdutos();
            for (Produto p : produtos) {
                if (p.getNomeProd().contains(jTextFieldCampoPesquisa.getText())) {
                    modelo.addRow(new Object[]{p.getProdId(), p.getNomeProd(), p.getDescricao(), p.getPrecoVenda(), p.getQuantidadeEstoque()});
                }
            }
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetalhesActionPerformed
        int indiceProd = jTableProdutos.getSelectedRow();
        if (indiceProd == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um produto para saber mais detalhes do produto.");
        } else {
            produto = produtos.get(indiceProd);
            JFrameDetalheProduto jFrameDetalheProduto = new JFrameDetalheProduto((produto));
        }
    }//GEN-LAST:event_jButtonDetalhesActionPerformed

    private void jButtonEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarProdutoActionPerformed
        int indiceProd = jTableProdutos.getSelectedRow();
        if (indiceProd == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um produto para saber mais detalhes do produto.");
        } else {
            Produto produto = produtos.get(indiceProd);
            JFrameEditarProduto jFrameEditarProduto = new JFrameEditarProduto((produto));
        }
    }//GEN-LAST:event_jButtonEditarProdutoActionPerformed

    private void jTextFieldCampoPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCampoPesquisaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jTextFieldCampoPesquisa.getText().equals("Nome do Produto")) {
                JOptionPane.showMessageDialog(null, "Digite um nome para realizar a pesquisa.");
            } else {
                modelo = (DefaultTableModel) jTableProdutos.getModel();
                modelo.setNumRows(0);
                produtos = new ControlaProduto().getListaProdutos();
                for (Produto p : produtos) {
                    if (p.getNomeProd().contains(jTextFieldCampoPesquisa.getText())) {
                        modelo.addRow(new Object[]{p.getProdId(), p.getNomeProd(), p.getDescricao(), p.getPrecoVenda(), p.getQuantidadeEstoque()});
                    }
                }
            }
    }//GEN-LAST:event_jTextFieldCampoPesquisaKeyPressed
    }
    private void jButtonAdicionarAoCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarAoCarrinhoActionPerformed
        // TODO add your handling code here:
        Date data = new Date();
        ControlaVenda controlaVenda = new ControlaVenda();
        if(idVenda == null){
            int n = JOptionPane.showConfirmDialog(
                    null,
                    "Não há nenhuma venda em andamento, gostaria de iniciar?",
                    "Confirmar Opção",
                    JOptionPane.YES_NO_OPTION);
            JPanel jPanelCarrinhoDeCompras;
            if (n == JOptionPane.YES_OPTION) {
                idVenda = funcionario.getIdFunc() + data.getTime();
                controlaVenda.novaVendaAberta(idVenda, funcionario);
                jInternalFrameAdicionandoAoCarrinho.setVisible(true);
            }

        }
        
    }//GEN-LAST:event_jButtonAdicionarAoCarrinhoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarAoCarrinho;
    private javax.swing.JButton jButtonDetalhes;
    private javax.swing.JButton jButtonEditarProduto;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JInternalFrame jInternalFrameAdicionandoAoCarrinho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNomeProduto;
    private javax.swing.JPanel jPanelConsultarProduto;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTextField jTextFieldCampoPesquisa;
    // End of variables declaration//GEN-END:variables
}
