/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControleProduto;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juliano
 */
public class JPanelConsultarProduto extends javax.swing.JPanel {

    /**
     * Creates new form JPanelConsultarProduto
     */
    DefaultTableModel modelo;
    ArrayList<Produto> produtos;
    Produto produto;

    public JPanelConsultarProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConsultarProduto = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jButtonDetalhes = new javax.swing.JButton();
        jLabelNomeProduto = new javax.swing.JLabel();
        jTextFieldCampoPesquisa = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonEditarProduto = new javax.swing.JButton();

        jPanelConsultarProduto.setMaximumSize(new java.awt.Dimension(999, 599));
        jPanelConsultarProduto.setMinimumSize(new java.awt.Dimension(999, 599));

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID:", "Nome:", "Descrição:", "Preço:", "Estoque:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProdutos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableProdutos);

        jButtonDetalhes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonDetalhes.setText("Detalhes");
        jButtonDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetalhesActionPerformed(evt);
            }
        });

        jLabelNomeProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelNomeProduto.setText("Nome do produto:");

        jTextFieldCampoPesquisa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jButtonPesquisar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonEditarProduto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonEditarProduto.setText("Editar");
        jButtonEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConsultarProdutoLayout = new javax.swing.GroupLayout(jPanelConsultarProduto);
        jPanelConsultarProduto.setLayout(jPanelConsultarProdutoLayout);
        jPanelConsultarProdutoLayout.setHorizontalGroup(
            jPanelConsultarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultarProdutoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonEditarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDetalhes))
                    .addGroup(jPanelConsultarProdutoLayout.createSequentialGroup()
                        .addComponent(jLabelNomeProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCampoPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisar)))
                .addContainerGap())
            .addGroup(jPanelConsultarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultarProdutoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelConsultarProdutoLayout.setVerticalGroup(
            jPanelConsultarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultarProdutoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelConsultarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeProduto)
                    .addComponent(jTextFieldCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 521, Short.MAX_VALUE)
                .addGroup(jPanelConsultarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDetalhes)
                    .addComponent(jButtonEditarProduto))
                .addContainerGap())
            .addGroup(jPanelConsultarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultarProdutoLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(68, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelConsultarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelConsultarProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        //BOTÃO DE PESQUISAR PRODUTOS
        if (jTextFieldCampoPesquisa.getText().equals("Nome do Produto")) {
            JOptionPane.showMessageDialog(null, "Digite um nome para realizar a pesquisa.");
        } else {
            modelo = (DefaultTableModel) jTableProdutos.getModel();
            modelo.setNumRows(0);
            produtos = new ControlaProduto().getListaProdutos();
            for (Produto p : produtos) {
                if (p.getNomeProd().contains(jTextFieldCampoPesquisa.getText())) {
                    modelo.addRow(new Object[]{p.getProdId(), p.getNomeProd(), p.getDescricao(), p.getPrecoVenda(), p.getQuantidadeEstoque()});
                }
            }
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetalhesActionPerformed
        // TODO add your handling code here:
        int indiceProd = jTableProdutos.getSelectedRow();
        if (indiceProd == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um produto para saber mais detalhes do produto.");
        } else {
            produto = produtos.get(indiceProd);
            JFrameDetalheProduto jFrameDetalheProduto = new JFrameDetalheProduto((produto));
        }
        
    }//GEN-LAST:event_jButtonDetalhesActionPerformed

    private void jButtonEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetalhes;
    private javax.swing.JButton jButtonEditarProduto;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JLabel jLabelNomeProduto;
    private javax.swing.JPanel jPanelConsultarProduto;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTextField jTextFieldCampoPesquisa;
    // End of variables declaration//GEN-END:variables
}
