/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GerenciamentoDeFuncionarios;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Juliano
 */
public class JPanelListaFuncionario extends javax.swing.JPanel {

    /**
     * Creates new form JPanelCadastroFuncionario
     */
    
    ArrayList <Funcionario> funcionarios;
    boolean ativos;
    
    public JPanelListaFuncionario() {
        initComponents();
        FetchFuncionarios();
    }
    
    public void FetchFuncionarios()
    {
        funcionarios = new ControlaFuncionario().getListaFuncionarios();
        Vector <String> nomes_func = new Vector();
        
        for(Funcionario f : funcionarios)
        {
            nomes_func.add(f.getNome());
        }

        this.jList1.setListData(nomes_func);
        this.jButtonLigDes.setVisible(false);
    }
    
    public void FetchFuncionarios(boolean ativos)
    {
        if(ativos)
            funcionarios = new ControlaFuncionario().getListaFuncionariosAtivos();
        else
            funcionarios = new ControlaFuncionario().getListaFuncionariosInativos();
            
        Vector <String> nomes_func = new Vector();
        
        for(Funcionario f : funcionarios)
        {
            nomes_func.add(f.getNome());
        }

        this.jList1.setListData(nomes_func);
        
        if(ativos)
            this.jButtonLigDes.setText("Desligar");
        else
            this.jButtonLigDes.setText("Reativar");
        
        this.jButtonLigDes.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVoltar = new javax.swing.JButton();
        jButtonConsultarCadastro = new javax.swing.JButton();
        jScrollPaneLista = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonConsultarFaltas = new javax.swing.JButton();
        jButtonLigDes = new javax.swing.JButton();

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonConsultarCadastro.setText("Consultar Cadastro");
        jButtonConsultarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarCadastroActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPaneLista.setViewportView(jList1);

        jLabelTitulo.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabelTitulo.setText("Selecione um funcionário:");

        jButtonConsultarFaltas.setText("Consultar Faltas");
        jButtonConsultarFaltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarFaltasActionPerformed(evt);
            }
        });

        jButtonLigDes.setText("DLFUNC");
        jButtonLigDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLigDesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneLista)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addGap(0, 702, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonVoltar)
                        .addGap(80, 80, 80)
                        .addComponent(jButtonLigDes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonConsultarFaltas)
                        .addGap(68, 68, 68)
                        .addComponent(jButtonConsultarCadastro)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneLista, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonLigDes)
                    .addComponent(jButtonVoltar)
                    .addComponent(jButtonConsultarFaltas)
                    .addComponent(jButtonConsultarCadastro))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        //this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonConsultarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarCadastroActionPerformed
        int indice = jList1.getSelectedIndex();

        if(indice != -1)
        {
            Funcionario fetchfun = this.funcionarios.get(indice);
            JFrame framecadastro = new FrameCadastroFuncionario(fetchfun);
        }
    }//GEN-LAST:event_jButtonConsultarCadastroActionPerformed

    private void jButtonConsultarFaltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarFaltasActionPerformed
        int indice = jList1.getSelectedIndex();

        if(indice != -1)
        {
            Funcionario fetchfun = this.funcionarios.get(indice);
            JFrame framefaltas = new FrameConsultarFrequencia(fetchfun);
        }
    }//GEN-LAST:event_jButtonConsultarFaltasActionPerformed

    private void jButtonLigDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLigDesActionPerformed
        int indice = jList1.getSelectedIndex();
        if(indice == -1)
        return;

        Funcionario fetchfun = this.funcionarios.get(indice);

        if(ativos)
        {
            fetchfun.setStatus(0);
        }
        else
        {
            fetchfun.setStatus(1);
        }

        boolean persistiu = new ControlaFuncionario().persisteFuncionario(fetchfun);
        if(persistiu){
            if(ativos)
            {
                JOptionPane.showMessageDialog(null, "Funcionario Desligado!");
                this.FetchFuncionarios(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Funcionario Reativado!");
                this.FetchFuncionarios(false);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao salvar alterações!");
        }
    }//GEN-LAST:event_jButtonLigDesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarCadastro;
    private javax.swing.JButton jButtonConsultarFaltas;
    private javax.swing.JButton jButtonLigDes;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPaneLista;
    // End of variables declaration//GEN-END:variables
}
