/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControleDeAcesso;

import GerenciamentoDeFuncionarios.Funcionario;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Juliano
 */
public class JPanelMinhaConta extends javax.swing.JPanel {

    /**
     * Creates new form JPanelMinhaConta
     */
    ArrayList<Acesso> acessos;
    Acesso acesso;
    Funcionario funcionario;

    public JPanelMinhaConta(Funcionario func) {
        initComponents();

        funcionario = func;

        acesso = new ControlaAcesso().buscaAcesso(funcionario);

        jTextFieldNomeCompleto.setText(func.getNome());
        jTextFieldLogin.setText(acesso.getLogin());

        jInternalFrameAcesso.setVisible(false);
        
        jPasswordFieldConfirmarSenha.setText("");
        jPasswordFieldNovaSenha.setText("");
        jPasswordFieldSenhaAtual.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jInternalFrameAcesso = new javax.swing.JInternalFrame();
        jLabelConfirmarSenha = new javax.swing.JLabel();
        jButtonSalvarSenhaAcesso = new javax.swing.JButton();
        jButtonFecharInternalFrame = new javax.swing.JButton();
        jLabelSenhaAtual = new javax.swing.JLabel();
        jLabelNovaSenha = new javax.swing.JLabel();
        jPasswordFieldConfirmarSenha = new javax.swing.JPasswordField();
        jPasswordFieldNovaSenha = new javax.swing.JPasswordField();
        jPasswordFieldSenhaAtual = new javax.swing.JPasswordField();
        jLabelNomeCompleto = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jTextFieldNomeCompleto = new javax.swing.JTextField();
        jTextFieldLogin = new javax.swing.JTextField();
        jButtonAlterarSenha = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Configurações de Conta");
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 34, 295, 46));

        jInternalFrameAcesso.setVisible(true);
        jInternalFrameAcesso.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelConfirmarSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelConfirmarSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelConfirmarSenha.setText("Confirmar Senha:");
        jInternalFrameAcesso.getContentPane().add(jLabelConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, 38));

        jButtonSalvarSenhaAcesso.setText("Salvar Senha");
        jButtonSalvarSenhaAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarSenhaAcessoActionPerformed(evt);
            }
        });
        jInternalFrameAcesso.getContentPane().add(jButtonSalvarSenhaAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 140, 40));

        jButtonFecharInternalFrame.setText("Cancelar");
        jButtonFecharInternalFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharInternalFrameActionPerformed(evt);
            }
        });
        jInternalFrameAcesso.getContentPane().add(jButtonFecharInternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 40));

        jLabelSenhaAtual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSenhaAtual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSenhaAtual.setText("Senha Atual:");
        jInternalFrameAcesso.getContentPane().add(jLabelSenhaAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 38));

        jLabelNovaSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNovaSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNovaSenha.setText("Nova Senha:");
        jInternalFrameAcesso.getContentPane().add(jLabelNovaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 38));

        jPasswordFieldConfirmarSenha.setText("jPasswordField1");
        jPasswordFieldConfirmarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldConfirmarSenhaActionPerformed(evt);
            }
        });
        jInternalFrameAcesso.getContentPane().add(jPasswordFieldConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 300, 40));

        jPasswordFieldNovaSenha.setText("jPasswordField1");
        jPasswordFieldNovaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldNovaSenhaActionPerformed(evt);
            }
        });
        jInternalFrameAcesso.getContentPane().add(jPasswordFieldNovaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 300, 40));

        jPasswordFieldSenhaAtual.setText("jPasswordField1");
        jPasswordFieldSenhaAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenhaAtualActionPerformed(evt);
            }
        });
        jInternalFrameAcesso.getContentPane().add(jPasswordFieldSenhaAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 300, 40));

        add(jInternalFrameAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 460, 280));

        jLabelNomeCompleto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNomeCompleto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNomeCompleto.setText("Nome Completo:");
        add(jLabelNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 160, -1, 20));

        jLabelLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLogin.setText("Meu Login:");
        add(jLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 220, 104, -1));

        jTextFieldNomeCompleto.setEditable(false);
        add(jTextFieldNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 162, 553, -1));

        jTextFieldLogin.setEditable(false);
        add(jTextFieldLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 217, 553, -1));

        jButtonAlterarSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAlterarSenha.setText("Alterar Minha Senha");
        jButtonAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarSenhaActionPerformed(evt);
            }
        });
        add(jButtonAlterarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 293, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarSenhaAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarSenhaAcessoActionPerformed
        // TODO add your handling code here:

        acessos = new ControlaAcesso().getListaAcessos();

        for (Acesso a : acessos) {
            if (a.getFuncionario().getIdFunc().equals(funcionario.getIdFunc())) {
                acesso = a;
                break;
            }
        }

        jPasswordFieldConfirmarSenha.setEnabled(false);
        jPasswordFieldNovaSenha.setEnabled(false);
        jPasswordFieldSenhaAtual.setEnabled(false);
        jButtonSalvarSenhaAcesso.setEnabled(false);
        jButtonFecharInternalFrame.setEnabled(false);

        if (jPasswordFieldSenhaAtual.getText().equals(acesso.getSenha())) {
            if (jPasswordFieldNovaSenha.getText().equals(jPasswordFieldConfirmarSenha.getText())) {
                acesso.setSenha(jPasswordFieldConfirmarSenha.getText());
                boolean persistiu = new ControlaAcesso().persisteAcesso(acesso);
                if (persistiu) {
                    jPasswordFieldConfirmarSenha.setEnabled(true);
                    jPasswordFieldNovaSenha.setEnabled(true);
                    jPasswordFieldSenhaAtual.setEnabled(true);
                    jButtonSalvarSenhaAcesso.setEnabled(true);
                    jButtonFecharInternalFrame.setEnabled(true);
                    JOptionPane.showMessageDialog(null, "Senha Alterada com Sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Erro na operação. Tente novamente!");
                    jPasswordFieldConfirmarSenha.setEnabled(true);
                    jPasswordFieldNovaSenha.setEnabled(true);
                    jPasswordFieldSenhaAtual.setEnabled(true);
                    jButtonSalvarSenhaAcesso.setEnabled(true);
                    jButtonFecharInternalFrame.setEnabled(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Nova Senha e Confirmar Senha Diferentes!");
                jPasswordFieldNovaSenha.setText("");
                jPasswordFieldConfirmarSenha.setText("");
                jPasswordFieldConfirmarSenha.setEnabled(true);
                jPasswordFieldNovaSenha.setEnabled(true);
                jPasswordFieldSenhaAtual.setEnabled(true);
                jButtonSalvarSenhaAcesso.setEnabled(true);
                jButtonFecharInternalFrame.setEnabled(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Senha Atual Incorreta!");
            jPasswordFieldSenhaAtual.setText("");
            jPasswordFieldConfirmarSenha.setEnabled(true);
            jPasswordFieldNovaSenha.setEnabled(true);
            jPasswordFieldSenhaAtual.setEnabled(true);
            jButtonSalvarSenhaAcesso.setEnabled(true);
            jButtonFecharInternalFrame.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonSalvarSenhaAcessoActionPerformed

    private void jButtonFecharInternalFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharInternalFrameActionPerformed
        // TODO add your handling code here:
        jInternalFrameAcesso.setVisible(false);
        jButtonAlterarSenha.setEnabled(true);
    }//GEN-LAST:event_jButtonFecharInternalFrameActionPerformed

    private void jButtonAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarSenhaActionPerformed
        // TODO add your handling code here:
        jInternalFrameAcesso.setVisible(true);
        jButtonAlterarSenha.setEnabled(false);
    }//GEN-LAST:event_jButtonAlterarSenhaActionPerformed

    private void jPasswordFieldConfirmarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldConfirmarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldConfirmarSenhaActionPerformed

    private void jPasswordFieldNovaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldNovaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldNovaSenhaActionPerformed

    private void jPasswordFieldSenhaAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSenhaAtualActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarSenha;
    private javax.swing.JButton jButtonFecharInternalFrame;
    private javax.swing.JButton jButtonSalvarSenhaAcesso;
    private javax.swing.JInternalFrame jInternalFrameAcesso;
    private javax.swing.JLabel jLabelConfirmarSenha;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelNomeCompleto;
    private javax.swing.JLabel jLabelNovaSenha;
    private javax.swing.JLabel jLabelSenhaAtual;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPasswordField jPasswordFieldConfirmarSenha;
    private javax.swing.JPasswordField jPasswordFieldNovaSenha;
    private javax.swing.JPasswordField jPasswordFieldSenhaAtual;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldNomeCompleto;
    // End of variables declaration//GEN-END:variables
}
