package Controle;
// Generated 07/10/2016 17:26:32 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Parcela generated by hbm2java
 */
public class Parcela  implements java.io.Serializable {


     private String parcelaId;
     private Vendas vendas;
     private Integer parcela;
     private Integer parcelaPaga;
     private Float valorTotal;
     private Float totalPago;
     private Float juros;
     private Date dataParcela;

    public Parcela() {
    }

	
    public Parcela(String parcelaId) {
        this.parcelaId = parcelaId;
    }
    public Parcela(String parcelaId, Vendas vendas, Integer parcela, Integer parcelaPaga, Float valorTotal, Float totalPago, Float juros, Date dataParcela) {
       this.parcelaId = parcelaId;
       this.vendas = vendas;
       this.parcela = parcela;
       this.parcelaPaga = parcelaPaga;
       this.valorTotal = valorTotal;
       this.totalPago = totalPago;
       this.juros = juros;
       this.dataParcela = dataParcela;
    }
   
    public String getParcelaId() {
        return this.parcelaId;
    }
    
    public void setParcelaId(String parcelaId) {
        this.parcelaId = parcelaId;
    }
    public Vendas getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Vendas vendas) {
        this.vendas = vendas;
    }
    public Integer getParcela() {
        return this.parcela;
    }
    
    public void setParcela(Integer parcela) {
        this.parcela = parcela;
    }
    public Integer getParcelaPaga() {
        return this.parcelaPaga;
    }
    
    public void setParcelaPaga(Integer parcelaPaga) {
        this.parcelaPaga = parcelaPaga;
    }
    public Float getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(Float valorTotal) {
        this.valorTotal = valorTotal;
    }
    public Float getTotalPago() {
        return this.totalPago;
    }
    
    public void setTotalPago(Float totalPago) {
        this.totalPago = totalPago;
    }
    public Float getJuros() {
        return this.juros;
    }
    
    public void setJuros(Float juros) {
        this.juros = juros;
    }
    public Date getDataParcela() {
        return this.dataParcela;
    }
    
    public void setDataParcela(Date dataParcela) {
        this.dataParcela = dataParcela;
    }




}


