/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import ControleDeAcesso.JFrameTelaLogin;
import GerenciamentoDeFuncionarios.Funcionario;
import javax.swing.Box;
import javax.swing.JOptionPane;

/**
 *
 * @author ander
 */
public class JFrameTelaGerente extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTelaGerente
     */
    public JFrameTelaGerente(Funcionario funcionario) {
        initComponents();
        
        this.setTitle("Gerente - " + funcionario.getNome());
        
        jMenuPrincipal.add(Box.createHorizontalGlue());
        jMenuPrincipal.add(jMenuSair);
    
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    private JFrameTelaGerente() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagemLogo = new javax.swing.JLabel();
        jPanelImagemFundo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jMenuPrincipal = new javax.swing.JMenuBar();
        jMenuFuncionario = new javax.swing.JMenu();
        jMenuCadastrarFuncionario = new javax.swing.JMenuItem();
        jMenuConsultarFuncionario = new javax.swing.JMenuItem();
        jMenuProduto = new javax.swing.JMenu();
        jMenuCadastrar = new javax.swing.JMenuItem();
        jMenuConsultar = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenu();
        jMenuVenda = new javax.swing.JMenu();
        jMenuCaixa = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerente - ");

        jLabelImagemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/redebras-topo-menor.jpg"))); // NOI18N

        jPanelImagemFundo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelImagemFundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelImagemFundo.setName(""); // NOI18N
        jPanelImagemFundo.setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo_gerente.png"))); // NOI18N

        javax.swing.GroupLayout jPanelImagemFundoLayout = new javax.swing.GroupLayout(jPanelImagemFundo);
        jPanelImagemFundo.setLayout(jPanelImagemFundoLayout);
        jPanelImagemFundoLayout.setHorizontalGroup(
            jPanelImagemFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagemFundoLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelImagemFundoLayout.setVerticalGroup(
            jPanelImagemFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagemFundoLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/shopping-cart-2-icon.png"))); // NOI18N

        jMenuFuncionario.setText("Funcionário");

        jMenuCadastrarFuncionario.setText("Cadastrar");
        jMenuCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarFuncionarioActionPerformed(evt);
            }
        });
        jMenuFuncionario.add(jMenuCadastrarFuncionario);

        jMenuConsultarFuncionario.setText("Consultar");
        jMenuFuncionario.add(jMenuConsultarFuncionario);

        jMenuPrincipal.add(jMenuFuncionario);

        jMenuProduto.setText("Produto");

        jMenuCadastrar.setText("Cadastrar");
        jMenuProduto.add(jMenuCadastrar);

        jMenuConsultar.setText("Consultar");
        jMenuConsultar.setToolTipText("");
        jMenuProduto.add(jMenuConsultar);

        jMenuPrincipal.add(jMenuProduto);

        jMenuCliente.setText("Cliente");
        jMenuPrincipal.add(jMenuCliente);

        jMenuVenda.setText("Venda");
        jMenuPrincipal.add(jMenuVenda);

        jMenuCaixa.setText("Caixa");
        jMenuPrincipal.add(jMenuCaixa);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuPrincipal.add(jMenuSair);

        setJMenuBar(jMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelImagemFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelImagemLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImagemLogo)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jPanelImagemFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCadastrarFuncionarioActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        // TODO add your handling code here:
        
        int n = JOptionPane.showConfirmDialog(
            null,
            "Deseja realmente sair?",
            "Confirmar Opção",
            JOptionPane.YES_NO_OPTION);

        if(n == JOptionPane.YES_OPTION){
            new JFrameTelaLogin();
            this.dispose();
        }
    }//GEN-LAST:event_jMenuSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTelaGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImagemLogo;
    private javax.swing.JMenuItem jMenuCadastrar;
    private javax.swing.JMenuItem jMenuCadastrarFuncionario;
    private javax.swing.JMenu jMenuCaixa;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenuItem jMenuConsultar;
    private javax.swing.JMenuItem jMenuConsultarFuncionario;
    private javax.swing.JMenu jMenuFuncionario;
    private javax.swing.JMenuBar jMenuPrincipal;
    private javax.swing.JMenu jMenuProduto;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuVenda;
    private javax.swing.JPanel jPanelImagemFundo;
    // End of variables declaration//GEN-END:variables

    private void title(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
