package Apresentacao;

import ControleDeAcesso.Acesso;
import ControleDeAcesso.ControlaAcesso;
import GerenciamentoDeFuncionarios.ControlaFuncionario;
import GerenciamentoDeFuncionarios.Funcionario;
import GerenciamentoDeFuncionarios.FrameCadastroFuncionario;
import ControleDeAcesso.JFrameTelaLogin;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juliano Cézar Chagas Tavares
 */
public class JFrameTelaAdmin extends javax.swing.JFrame {

    ArrayList<Funcionario> funcionarios;
    Acesso acesso = null;

    public JFrameTelaAdmin() {
        initComponents();

        jInternalFrameAcesso.setVisible(false);
        jButtonSalvarSenhaAcesso.setVisible(false);
        jInternalFrameAcesso.setTitle("Gerenciar Acesso");
        jTextFieldSenhaAcesso.setEnabled(false);

        jButtonConsultarFunc.setVisible(false);
        jButtonGerenciarAcesso.setVisible(false);

        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEncerrarSessao = new javax.swing.JButton();
        jPanelPrincipal = new javax.swing.JPanel();
        jTabbedPaneFuncionario = new javax.swing.JTabbedPane();
        jPanelCadastrarFuncionario = new javax.swing.JPanel();
        jLabelDataNascimentoFunc = new javax.swing.JLabel();
        jLabelComplementoFunc = new javax.swing.JLabel();
        jLabelEnderecoFunc = new javax.swing.JLabel();
        jLabelCPFFunc = new javax.swing.JLabel();
        jLabelRGFunc = new javax.swing.JLabel();
        jLabelNomeCompletoFunc = new javax.swing.JLabel();
        jLabelTelefoneFunc = new javax.swing.JLabel();
        jLabelEstadoCivilFunc = new javax.swing.JLabel();
        jLabelCabecalho1 = new javax.swing.JLabel();
        jLabelNumeroFunc = new javax.swing.JLabel();
        jLabelBairroFunc = new javax.swing.JLabel();
        jLabelCidadeFunc = new javax.swing.JLabel();
        jLabelCEPfunc = new javax.swing.JLabel();
        jLabelEstadoFunc = new javax.swing.JLabel();
        jLabelSexoFunc = new javax.swing.JLabel();
        jLabelNomeConjugeFunc = new javax.swing.JLabel();
        jTextFieldNomeCompleto = new javax.swing.JTextField();
        jTextFieldRG2 = new javax.swing.JTextField();
        jComboBoxSexo2 = new javax.swing.JComboBox<>();
        jTextFieldCPF2 = new javax.swing.JTextField();
        jTextFieldEndereco2 = new javax.swing.JTextField();
        jTextFieldCEP2 = new javax.swing.JTextField();
        jTextFieldNumero2 = new javax.swing.JTextField();
        jTextFieldComplemento2 = new javax.swing.JTextField();
        jTextFieldBairro2 = new javax.swing.JTextField();
        jTextFieldCidade2 = new javax.swing.JTextField();
        jTextFieldEstado2 = new javax.swing.JTextField();
        jComboBoxEstadoCivil2 = new javax.swing.JComboBox<>();
        jTextFieldNomeConjuge = new javax.swing.JTextField();
        jTextFieldTelefone = new javax.swing.JTextField();
        jFormattedTextFieldDataNascimento2 = new javax.swing.JFormattedTextField();
        jLabelDataContratacaoFunc = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabelCargoFunc = new javax.swing.JLabel();
        jComboBoxCargo = new javax.swing.JComboBox<>();
        jLabelLoginFunc = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabelSenhaFunc = new javax.swing.JLabel();
        jTextFieldSenha = new javax.swing.JTextField();
        jButtonConfirmarFunc = new javax.swing.JButton();
        jPanelConsultarFuncionario = new javax.swing.JPanel();
        jInternalFrameAcesso = new javax.swing.JInternalFrame();
        jLabelNomeAcesso = new javax.swing.JLabel();
        jLabelSenhaAcesso = new javax.swing.JLabel();
        jLabelLoginAcesso = new javax.swing.JLabel();
        jTextFieldSenhaAcesso = new javax.swing.JTextField();
        jButtonAlterarSenhaAcesso = new javax.swing.JButton();
        jButtonSalvarSenhaAcesso = new javax.swing.JButton();
        jButtonFecharInternalFrame = new javax.swing.JButton();
        jScrollPaneTabelaFuncionarios = new javax.swing.JScrollPane();
        jTableFuncionarios = new javax.swing.JTable();
        jButtonListarFunc = new javax.swing.JButton();
        jButtonConsultarFunc = new javax.swing.JButton();
        jButtonGerenciarAcesso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonEncerrarSessao.setText("Encerrar Sessão");
        jButtonEncerrarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncerrarSessaoActionPerformed(evt);
            }
        });

        jPanelCadastrarFuncionario.setLayout(null);

        jLabelDataNascimentoFunc.setText("Data de Nascimento");
        jPanelCadastrarFuncionario.add(jLabelDataNascimentoFunc);
        jLabelDataNascimentoFunc.setBounds(0, 290, 110, 30);

        jLabelComplementoFunc.setText("Complemento");
        jPanelCadastrarFuncionario.add(jLabelComplementoFunc);
        jLabelComplementoFunc.setBounds(20, 240, 80, 30);

        jLabelEnderecoFunc.setText("Endereço");
        jPanelCadastrarFuncionario.add(jLabelEnderecoFunc);
        jLabelEnderecoFunc.setBounds(30, 190, 70, 30);

        jLabelCPFFunc.setText("CPF");
        jPanelCadastrarFuncionario.add(jLabelCPFFunc);
        jLabelCPFFunc.setBounds(490, 140, 40, 30);

        jLabelRGFunc.setText("RG");
        jPanelCadastrarFuncionario.add(jLabelRGFunc);
        jLabelRGFunc.setBounds(70, 140, 30, 30);

        jLabelNomeCompletoFunc.setText("Nome");
        jPanelCadastrarFuncionario.add(jLabelNomeCompletoFunc);
        jLabelNomeCompletoFunc.setBounds(60, 90, 40, 30);

        jLabelTelefoneFunc.setText("Telefone Fixo");
        jPanelCadastrarFuncionario.add(jLabelTelefoneFunc);
        jLabelTelefoneFunc.setBounds(460, 340, 80, 30);

        jLabelEstadoCivilFunc.setText("Estado Civil");
        jPanelCadastrarFuncionario.add(jLabelEstadoCivilFunc);
        jLabelEstadoCivilFunc.setBounds(230, 290, 70, 30);

        jLabelCabecalho1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCabecalho1.setText("Cadastro de Novo Funcionario");
        jPanelCadastrarFuncionario.add(jLabelCabecalho1);
        jLabelCabecalho1.setBounds(356, 20, 210, 31);

        jLabelNumeroFunc.setText("Número");
        jPanelCadastrarFuncionario.add(jLabelNumeroFunc);
        jLabelNumeroFunc.setBounds(480, 240, 60, 30);

        jLabelBairroFunc.setText("Bairro");
        jPanelCadastrarFuncionario.add(jLabelBairroFunc);
        jLabelBairroFunc.setBounds(260, 240, 50, 30);

        jLabelCidadeFunc.setText("Cidade");
        jPanelCadastrarFuncionario.add(jLabelCidadeFunc);
        jLabelCidadeFunc.setBounds(650, 240, 40, 30);

        jLabelCEPfunc.setText("CEP");
        jPanelCadastrarFuncionario.add(jLabelCEPfunc);
        jLabelCEPfunc.setBounds(640, 190, 40, 30);

        jLabelEstadoFunc.setText("Estado");
        jPanelCadastrarFuncionario.add(jLabelEstadoFunc);
        jLabelEstadoFunc.setBounds(820, 240, 50, 30);

        jLabelSexoFunc.setText("Sexo");
        jPanelCadastrarFuncionario.add(jLabelSexoFunc);
        jLabelSexoFunc.setBounds(780, 90, 40, 30);

        jLabelNomeConjugeFunc.setText("Nome Conjuge");
        jPanelCadastrarFuncionario.add(jLabelNomeConjugeFunc);
        jLabelNomeConjugeFunc.setBounds(20, 340, 80, 30);

        jTextFieldNomeCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeCompletoActionPerformed(evt);
            }
        });
        jPanelCadastrarFuncionario.add(jTextFieldNomeCompleto);
        jTextFieldNomeCompleto.setBounds(110, 90, 660, 30);
        jPanelCadastrarFuncionario.add(jTextFieldRG2);
        jTextFieldRG2.setBounds(110, 140, 360, 30);

        jComboBoxSexo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jPanelCadastrarFuncionario.add(jComboBoxSexo2);
        jComboBoxSexo2.setBounds(810, 90, 120, 30);
        jPanelCadastrarFuncionario.add(jTextFieldCPF2);
        jTextFieldCPF2.setBounds(520, 140, 410, 30);
        jPanelCadastrarFuncionario.add(jTextFieldEndereco2);
        jTextFieldEndereco2.setBounds(110, 190, 510, 30);
        jPanelCadastrarFuncionario.add(jTextFieldCEP2);
        jTextFieldCEP2.setBounds(670, 190, 260, 30);
        jPanelCadastrarFuncionario.add(jTextFieldNumero2);
        jTextFieldNumero2.setBounds(530, 240, 110, 30);

        jTextFieldComplemento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldComplemento2ActionPerformed(evt);
            }
        });
        jPanelCadastrarFuncionario.add(jTextFieldComplemento2);
        jTextFieldComplemento2.setBounds(110, 240, 140, 30);
        jPanelCadastrarFuncionario.add(jTextFieldBairro2);
        jTextFieldBairro2.setBounds(300, 240, 170, 30);
        jPanelCadastrarFuncionario.add(jTextFieldCidade2);
        jTextFieldCidade2.setBounds(690, 240, 120, 30);
        jPanelCadastrarFuncionario.add(jTextFieldEstado2);
        jTextFieldEstado2.setBounds(860, 240, 70, 30);

        jComboBoxEstadoCivil2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro(a)", "Casado(a)", "Viúvo(a)", "Divorciado(a)" }));
        jComboBoxEstadoCivil2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelCadastrarFuncionario.add(jComboBoxEstadoCivil2);
        jComboBoxEstadoCivil2.setBounds(300, 290, 130, 30);
        jPanelCadastrarFuncionario.add(jTextFieldNomeConjuge);
        jTextFieldNomeConjuge.setBounds(110, 340, 340, 30);
        jPanelCadastrarFuncionario.add(jTextFieldTelefone);
        jTextFieldTelefone.setBounds(540, 340, 390, 30);

        jFormattedTextFieldDataNascimento2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextFieldDataNascimento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDataNascimento2ActionPerformed(evt);
            }
        });
        jPanelCadastrarFuncionario.add(jFormattedTextFieldDataNascimento2);
        jFormattedTextFieldDataNascimento2.setBounds(110, 290, 110, 30);

        jLabelDataContratacaoFunc.setText("Data de Contratação");
        jPanelCadastrarFuncionario.add(jLabelDataContratacaoFunc);
        jLabelDataContratacaoFunc.setBounds(440, 294, 110, 30);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        jPanelCadastrarFuncionario.add(jFormattedTextField1);
        jFormattedTextField1.setBounds(550, 290, 170, 30);

        jLabelCargoFunc.setText("Cargo");
        jPanelCadastrarFuncionario.add(jLabelCargoFunc);
        jLabelCargoFunc.setBounds(730, 290, 50, 30);

        jComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Almoxarife", "Contador(a)", "Gerente", "Vendedor(a)" }));
        jComboBoxCargo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelCadastrarFuncionario.add(jComboBoxCargo);
        jComboBoxCargo.setBounds(770, 290, 160, 30);

        jLabelLoginFunc.setText("Login");
        jPanelCadastrarFuncionario.add(jLabelLoginFunc);
        jLabelLoginFunc.setBounds(50, 390, 40, 30);
        jPanelCadastrarFuncionario.add(jTextFieldLogin);
        jTextFieldLogin.setBounds(110, 390, 340, 30);

        jLabelSenhaFunc.setText("Senha");
        jPanelCadastrarFuncionario.add(jLabelSenhaFunc);
        jLabelSenhaFunc.setBounds(470, 390, 50, 30);
        jPanelCadastrarFuncionario.add(jTextFieldSenha);
        jTextFieldSenha.setBounds(540, 390, 390, 30);

        jButtonConfirmarFunc.setText("Confirmar");
        jButtonConfirmarFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConfirmarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarFuncActionPerformed(evt);
            }
        });
        jPanelCadastrarFuncionario.add(jButtonConfirmarFunc);
        jButtonConfirmarFunc.setBounds(820, 470, 100, 50);

        jTabbedPaneFuncionario.addTab("Cadastro", jPanelCadastrarFuncionario);

        jPanelConsultarFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrameAcesso.setVisible(true);
        jInternalFrameAcesso.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNomeAcesso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jInternalFrameAcesso.getContentPane().add(jLabelNomeAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 424, 33));

        jLabelSenhaAcesso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSenhaAcesso.setText("Senha Acesso:");
        jInternalFrameAcesso.getContentPane().add(jLabelSenhaAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 121, 81, 38));

        jLabelLoginAcesso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jInternalFrameAcesso.getContentPane().add(jLabelLoginAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, 424, 38));
        jInternalFrameAcesso.getContentPane().add(jTextFieldSenhaAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 121, 325, 38));

        jButtonAlterarSenhaAcesso.setText("Alterar Senha");
        jButtonAlterarSenhaAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarSenhaAcessoActionPerformed(evt);
            }
        });
        jInternalFrameAcesso.getContentPane().add(jButtonAlterarSenhaAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 140, 40));

        jButtonSalvarSenhaAcesso.setText("Salvar Senha");
        jButtonSalvarSenhaAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarSenhaAcessoActionPerformed(evt);
            }
        });
        jInternalFrameAcesso.getContentPane().add(jButtonSalvarSenhaAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 140, 40));

        jButtonFecharInternalFrame.setText("Fechar");
        jButtonFecharInternalFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharInternalFrameActionPerformed(evt);
            }
        });
        jInternalFrameAcesso.getContentPane().add(jButtonFecharInternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 199, 110, 40));

        jPanelConsultarFuncionario.add(jInternalFrameAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 460, 280));

        jTableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFuncionarios.getTableHeader().setReorderingAllowed(false);
        jScrollPaneTabelaFuncionarios.setViewportView(jTableFuncionarios);

        jPanelConsultarFuncionario.add(jScrollPaneTabelaFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 24, 958, 404));

        jButtonListarFunc.setText("Listar Funcionários");
        jButtonListarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarFuncActionPerformed(evt);
            }
        });
        jPanelConsultarFuncionario.add(jButtonListarFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 473, 190, 50));

        jButtonConsultarFunc.setText("Consultar");
        jButtonConsultarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarFuncActionPerformed(evt);
            }
        });
        jPanelConsultarFuncionario.add(jButtonConsultarFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 473, 120, 50));

        jButtonGerenciarAcesso.setText("Gerenciar Acesso");
        jButtonGerenciarAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciarAcessoActionPerformed(evt);
            }
        });
        jPanelConsultarFuncionario.add(jButtonGerenciarAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 470, 170, 60));

        jTabbedPaneFuncionario.addTab("Consulta", jPanelConsultarFuncionario);

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPaneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPaneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(jButtonEncerrarSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 973, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEncerrarSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEncerrarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncerrarSessaoActionPerformed
        // TODO add your handling code here:
        dispose();
        JFrameTelaLogin jFrameTelaLogin = new JFrameTelaLogin();
    }//GEN-LAST:event_jButtonEncerrarSessaoActionPerformed

    private void jTextFieldNomeCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeCompletoActionPerformed

    private void jTextFieldComplemento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldComplemento2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldComplemento2ActionPerformed

    private void jFormattedTextFieldDataNascimento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataNascimento2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDataNascimento2ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jButtonConfirmarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarFuncActionPerformed
        // TODO add your handling code here:
        if (jTextFieldBairro2.getText().equals("")
                || jTextFieldCEP2.getText().equals("")
                || jTextFieldCPF2.getText().equals("")
                || jTextFieldCidade2.getText().equals("")
                || jTextFieldEndereco2.getText().equals("")
                || jTextFieldEstado2.getText().equals("")
                || jTextFieldLogin.getText().equals("")
                || jTextFieldNomeCompleto.getText().equals("")
                || jTextFieldNumero2.getText().equals("")
                || jTextFieldRG2.getText().equals("")
                || jTextFieldSenha.getText().equals("")
                || jTextFieldTelefone.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        } else if (jComboBoxEstadoCivil2.getSelectedItem().toString().equals("Casado(a)") && jTextFieldNomeConjuge.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira o nome do Conjuge!");
        } else {
            jButtonConfirmarFunc.setEnabled(false);
            int cargo = 10;
            switch (jComboBoxCargo.getSelectedItem().toString()) {
                case "Almoxarife":
                    cargo = 3;
                    break;
                case "Contador(a)":
                    cargo = 2;
                    break;
                case "Vendedor(a)":
                    cargo = 1;
                    break;
                case "Gerente":
                    cargo = 0;
            }
            DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date dateNasc = null;
            java.sql.Date dateContrat = null;

            try {
                dateNasc = new java.sql.Date(((java.util.Date) formatter.parse(jFormattedTextFieldDataNascimento2.getText())).getTime());
            } catch (ParseException ex) {
                Logger.getLogger(JFrameTelaAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                dateContrat = new java.sql.Date(((java.util.Date) formatter.parse(jFormattedTextField1.getText())).getTime());
            } catch (ParseException ex) {
                Logger.getLogger(JFrameTelaAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }

            ControlaFuncionario controlaFuncionario = new ControlaFuncionario();
            if (!controlaFuncionario.funcionarioCadastrado(jTextFieldCPF2.getText())) {
                ControlaAcesso controlaAcesso = new ControlaAcesso();
                if (!controlaAcesso.loginCadastrado(jTextFieldLogin.getText())) {
                    try {
                        Funcionario funcionario = new ControlaFuncionario().criarFuncionario(jTextFieldCPF2.getText(), jTextFieldNomeCompleto.getText(), jTextFieldCPF2.getText(), jTextFieldRG2.getText(), dateNasc, jComboBoxEstadoCivil2.getSelectedItem().toString(), jTextFieldNomeConjuge.getText(), jTextFieldEndereco2.getText(), jTextFieldNumero2.getText(), jTextFieldComplemento2.getText(), jTextFieldCidade2.getText(), jTextFieldEstado2.getText(), jComboBoxCargo.getSelectedItem().toString(), dateContrat, cargo, jComboBoxSexo2.getSelectedItem().toString(), jTextFieldBairro2.getText(), jTextFieldCEP2.getText(), jTextFieldTelefone.getText(), 1);
                        new ControlaAcesso().criarAcesso(jTextFieldLogin.getText(), funcionario, jTextFieldSenha.getText());
                        limpaCampos();
                        JOptionPane.showMessageDialog(null, "Usuário Cadastrado com Sucesso!");
                        jButtonConfirmarFunc.setEnabled(true);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "ERRO! Usuário não Cadastrado");
                        jButtonConfirmarFunc.setEnabled(true);
                    }
                }
            }
    }//GEN-LAST:event_jButtonConfirmarFuncActionPerformed
    }
    private void jButtonListarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarFuncActionPerformed
        // TODO add your handling code here:
        funcionarios = new ControlaFuncionario().getListaFuncionarios();
        jButtonConsultarFunc.setVisible(true);
        jButtonGerenciarAcesso.setVisible(true);
        //jButtonListarFunc.setVisible(false);

        DefaultTableModel modelo = (DefaultTableModel) jTableFuncionarios.getModel();
        modelo.setNumRows(0);
        for (Funcionario f : funcionarios) {
            modelo.addRow(new Object[]{f.getIdFunc(), f.getNome(), f.getCargo()});
        }
        jButtonConsultarFunc.setVisible(true);

    }//GEN-LAST:event_jButtonListarFuncActionPerformed

    private void jButtonConsultarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarFuncActionPerformed
        // TODO add your handling code here:
        int indice = jTableFuncionarios.getSelectedRow();
        if (indice == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um funcionário!");
        } else {
            Funcionario funcionario = funcionarios.get(indice);
            new FrameCadastroFuncionario((funcionario));
        }
    }//GEN-LAST:event_jButtonConsultarFuncActionPerformed

    private void jButtonGerenciarAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarAcessoActionPerformed
        // TODO add your handling code here:

        int indice = jTableFuncionarios.getSelectedRow();
        if (indice == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um funcionário!");
        } else {
            Funcionario funcionario = funcionarios.get(indice);
            ArrayList<Acesso> acessos = new ControlaAcesso().getListaAcessos();

            boolean temAcesso = false;

            for (Acesso a : acessos) {
                if (a.getFuncionario().getIdFunc().equals(funcionario.getIdFunc())) {
                    acesso = a;
                    temAcesso = true;
                    break;
                }
            }
            if (temAcesso) {
                jLabelNomeAcesso.setText("Nome: " + funcionario.getNome());
                jLabelLoginAcesso.setText("Login: " + acesso.getLogin());
                jTextFieldSenhaAcesso.setText(acesso.getSenha());
                jInternalFrameAcesso.setVisible(true);
                desativaConsulta(false);
            } else {
                JOptionPane.showMessageDialog(null, "Este funcionário não possui acesso!");
            }

        }
    }//GEN-LAST:event_jButtonGerenciarAcessoActionPerformed

    private void jButtonAlterarSenhaAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarSenhaAcessoActionPerformed
        // TODO add your handling code here:
        jButtonFecharInternalFrame.setVisible(false);
        jButtonAlterarSenhaAcesso.setVisible(false);
        jButtonSalvarSenhaAcesso.setVisible(true);
        jTextFieldSenhaAcesso.setEnabled(true);
    }//GEN-LAST:event_jButtonAlterarSenhaAcessoActionPerformed

    private void jButtonSalvarSenhaAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarSenhaAcessoActionPerformed
        // TODO add your handling code here:
        jTextFieldSenhaAcesso.setEnabled(false);
        acesso.setSenha(jTextFieldSenhaAcesso.getText());
        boolean persistiu = new ControlaAcesso().persisteAcesso(acesso);
        if (persistiu) {
            jButtonAlterarSenhaAcesso.setVisible(true);
            jButtonFecharInternalFrame.setVisible(true);
            jButtonSalvarSenhaAcesso.setVisible(false);
            JOptionPane.showMessageDialog(null, "Senha Alterada com Sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Erro na operação. Tente novamente!");
            jTextFieldSenhaAcesso.setEnabled(true);
        }

    }//GEN-LAST:event_jButtonSalvarSenhaAcessoActionPerformed

    private void jButtonFecharInternalFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharInternalFrameActionPerformed
        // TODO add your handling code here:
        jInternalFrameAcesso.setVisible(false);
        desativaConsulta(true);
    }//GEN-LAST:event_jButtonFecharInternalFrameActionPerformed

    public void limpaCampos() {
        jTextFieldBairro2.setText("");
        jTextFieldCEP2.setText("");
        jTextFieldCPF2.setText("");
        jTextFieldCidade2.setText("");
        jTextFieldComplemento2.setText("");
        jTextFieldEndereco2.setText("");
        jTextFieldEstado2.setText("");
        jTextFieldLogin.setText("");
        jTextFieldNomeCompleto.setText("");
        jTextFieldNomeConjuge.setText("");
        jTextFieldNumero2.setText("");
        jTextFieldRG2.setText("");
        jTextFieldSenha.setText("");
        jTextFieldTelefone.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTelaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarSenhaAcesso;
    private javax.swing.JButton jButtonConfirmarFunc;
    private javax.swing.JButton jButtonConsultarFunc;
    private javax.swing.JButton jButtonEncerrarSessao;
    private javax.swing.JButton jButtonFecharInternalFrame;
    private javax.swing.JButton jButtonGerenciarAcesso;
    private javax.swing.JButton jButtonListarFunc;
    private javax.swing.JButton jButtonSalvarSenhaAcesso;
    private javax.swing.JComboBox<String> jComboBoxCargo;
    private javax.swing.JComboBox<String> jComboBoxEstadoCivil2;
    private javax.swing.JComboBox<String> jComboBoxSexo2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNascimento2;
    private javax.swing.JInternalFrame jInternalFrameAcesso;
    private javax.swing.JLabel jLabelBairroFunc;
    private javax.swing.JLabel jLabelCEPfunc;
    private javax.swing.JLabel jLabelCPFFunc;
    private javax.swing.JLabel jLabelCabecalho1;
    private javax.swing.JLabel jLabelCargoFunc;
    private javax.swing.JLabel jLabelCidadeFunc;
    private javax.swing.JLabel jLabelComplementoFunc;
    private javax.swing.JLabel jLabelDataContratacaoFunc;
    private javax.swing.JLabel jLabelDataNascimentoFunc;
    private javax.swing.JLabel jLabelEnderecoFunc;
    private javax.swing.JLabel jLabelEstadoCivilFunc;
    private javax.swing.JLabel jLabelEstadoFunc;
    private javax.swing.JLabel jLabelLoginAcesso;
    private javax.swing.JLabel jLabelLoginFunc;
    private javax.swing.JLabel jLabelNomeAcesso;
    private javax.swing.JLabel jLabelNomeCompletoFunc;
    private javax.swing.JLabel jLabelNomeConjugeFunc;
    private javax.swing.JLabel jLabelNumeroFunc;
    private javax.swing.JLabel jLabelRGFunc;
    private javax.swing.JLabel jLabelSenhaAcesso;
    private javax.swing.JLabel jLabelSenhaFunc;
    private javax.swing.JLabel jLabelSexoFunc;
    private javax.swing.JLabel jLabelTelefoneFunc;
    private javax.swing.JPanel jPanelCadastrarFuncionario;
    private javax.swing.JPanel jPanelConsultarFuncionario;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPaneTabelaFuncionarios;
    private javax.swing.JTabbedPane jTabbedPaneFuncionario;
    private javax.swing.JTable jTableFuncionarios;
    private javax.swing.JTextField jTextFieldBairro2;
    private javax.swing.JTextField jTextFieldCEP2;
    private javax.swing.JTextField jTextFieldCPF2;
    private javax.swing.JTextField jTextFieldCidade2;
    private javax.swing.JTextField jTextFieldComplemento2;
    private javax.swing.JTextField jTextFieldEndereco2;
    private javax.swing.JTextField jTextFieldEstado2;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldNomeCompleto;
    private javax.swing.JTextField jTextFieldNomeConjuge;
    private javax.swing.JTextField jTextFieldNumero2;
    private javax.swing.JTextField jTextFieldRG2;
    private javax.swing.JTextField jTextFieldSenha;
    private javax.swing.JTextField jTextFieldSenhaAcesso;
    private javax.swing.JTextField jTextFieldTelefone;
    // End of variables declaration//GEN-END:variables

    private void desativaConsulta(boolean bool) {

        jTabbedPaneFuncionario.setEnabled(bool);
        jTableFuncionarios.setEnabled(bool);
        jButtonListarFunc.setEnabled(bool);
        jButtonConsultarFunc.setEnabled(bool);
        jButtonGerenciarAcesso.setEnabled(bool);
        jButtonEncerrarSessao.setEnabled(bool);
    }
}
