/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import ControleCliente.JPanelConsultaCliente;
import ControleDeAcesso.JFrameTelaLogin;
import ControleDeAcesso.JPanelMinhaConta;
import ControleDeVendas.ControlaVenda;
import ControleDeVendas.JPanelCarrinhoDeCompras;
import ControleDeVendas.VendaAberta;
import ControleEstoque.JPanelListaDePedidosDeReposicao;
import ControleEstoque.JPanelPedidoReposicaoEstoque;
import ControleProduto.JPanelCadastrarProduto;
import ControleProduto.JPanelConsultarProduto;
import GerenciamentoDeFuncionarios.Funcionario;
import GerenciamentoDeFuncionarios.JPanelCadastroFuncionario;
import GerenciamentoDeFuncionarios.JPanelListaFuncionario;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class JFrameTelaGerente extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTelaGerente
     */
    CardLayout card;
    Funcionario funcionario;
    VendaAberta vendaAberta;

    public JFrameTelaGerente(Funcionario func) {
        initComponents();

        funcionario = func;

        this.setTitle("Gerente - " + funcionario.getNome());

        jMenuPrincipal.add(Box.createHorizontalGlue());
        jMenuPrincipal.add(jMenuSair);
        jMenuPrincipal.add(jMenuMinhaConta);

        jButtonCarrinho.setContentAreaFilled(false);
        jButtonCarrinho.setBorderPainted(false);

        JPanel jPanelImagemFundo = new JPanelImagemFundo();
        card = (CardLayout) jPanelFundo.getLayout();
        jPanelFundo.add(jPanelImagemFundo);
        card.show(jPanelFundo, "jPanelImagemFundo");

        jPanelFundo.setBorder(null);
        this.setLocationRelativeTo(null);
        jPanelFundo.setBorder(null);
        this.setVisible(true);
    }

    private JFrameTelaGerente() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagemLogo = new javax.swing.JLabel();
        jPanelFundo = new javax.swing.JPanel();
        jButtonCarrinho = new javax.swing.JButton();
        jMenuPrincipal = new javax.swing.JMenuBar();
        jMenuFuncionario = new javax.swing.JMenu();
        jMenuCadastrarFuncionario = new javax.swing.JMenuItem();
        jMenuConsultarFuncionario = new javax.swing.JMenuItem();
        jMenuProduto = new javax.swing.JMenu();
        jMenuCadastrarProduto = new javax.swing.JMenuItem();
        jMenuConsultarProduto = new javax.swing.JMenuItem();
        jMenuPedido = new javax.swing.JMenu();
        jMenuItemNovoPedido = new javax.swing.JMenuItem();
        jMenuItemPedidosRep = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenu();
        jMenuCadastrarCliente = new javax.swing.JMenuItem();
        jMenuConsultarCliente = new javax.swing.JMenuItem();
        jMenuVenda = new javax.swing.JMenu();
        jMenuCadastrarVenda = new javax.swing.JMenuItem();
        jMenuCaixa = new javax.swing.JMenu();
        jMenuConsultarCaixa = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuMinhaConta = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerente - ");
        setResizable(false);

        jLabelImagemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/redebras-topo-menor.jpg"))); // NOI18N

        jPanelFundo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelFundo.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanelFundo.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanelFundo.setName(""); // NOI18N
        jPanelFundo.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanelFundo.setLayout(new java.awt.CardLayout());

        jButtonCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/shopping-cart-2-icon.png"))); // NOI18N
        jButtonCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarrinhoActionPerformed(evt);
            }
        });

        jMenuFuncionario.setText("Funcionário");

        jMenuCadastrarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/new20x20.png"))); // NOI18N
        jMenuCadastrarFuncionario.setText("Novo");
        jMenuCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarFuncionarioActionPerformed(evt);
            }
        });
        jMenuFuncionario.add(jMenuCadastrarFuncionario);

        jMenuConsultarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/search20x20.png"))); // NOI18N
        jMenuConsultarFuncionario.setText("Buscar");
        jMenuConsultarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultarFuncionarioActionPerformed(evt);
            }
        });
        jMenuFuncionario.add(jMenuConsultarFuncionario);

        jMenuPrincipal.add(jMenuFuncionario);

        jMenuProduto.setText("Produto");

        jMenuCadastrarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/simpleNew20x20.png"))); // NOI18N
        jMenuCadastrarProduto.setText("Novo");
        jMenuCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarProdutoActionPerformed(evt);
            }
        });
        jMenuProduto.add(jMenuCadastrarProduto);

        jMenuConsultarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/search20x20.png"))); // NOI18N
        jMenuConsultarProduto.setText("Buscar");
        jMenuConsultarProduto.setToolTipText("");
        jMenuConsultarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultarProdutoActionPerformed(evt);
            }
        });
        jMenuProduto.add(jMenuConsultarProduto);

        jMenuPrincipal.add(jMenuProduto);

        jMenuPedido.setText("Pedidos");

        jMenuItemNovoPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/simpleNew20x20.png"))); // NOI18N
        jMenuItemNovoPedido.setText("Novo");
        jMenuItemNovoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovoPedidoActionPerformed(evt);
            }
        });
        jMenuPedido.add(jMenuItemNovoPedido);

        jMenuItemPedidosRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/search20x20.png"))); // NOI18N
        jMenuItemPedidosRep.setText("Buscar");
        jMenuItemPedidosRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPedidosRepActionPerformed(evt);
            }
        });
        jMenuPedido.add(jMenuItemPedidosRep);

        jMenuPrincipal.add(jMenuPedido);

        jMenuCliente.setText("Cliente");

        jMenuCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/new20x20.png"))); // NOI18N
        jMenuCadastrarCliente.setText("Novo");
        jMenuCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuCadastrarCliente);

        jMenuConsultarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/search20x20.png"))); // NOI18N
        jMenuConsultarCliente.setText("Buscar");
        jMenuConsultarCliente.setToolTipText("");
        jMenuConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultarClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuConsultarCliente);

        jMenuPrincipal.add(jMenuCliente);

        jMenuVenda.setText("Venda");

        jMenuCadastrarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/new20x20.png"))); // NOI18N
        jMenuCadastrarVenda.setText("Novo");
        jMenuCadastrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarVendaActionPerformed(evt);
            }
        });
        jMenuVenda.add(jMenuCadastrarVenda);

        jMenuPrincipal.add(jMenuVenda);

        jMenuCaixa.setText("Caixa");

        jMenuConsultarCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/search20x20.png"))); // NOI18N
        jMenuConsultarCaixa.setText("Consultar");
        jMenuConsultarCaixa.setToolTipText("");
        jMenuCaixa.add(jMenuConsultarCaixa);

        jMenuPrincipal.add(jMenuCaixa);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuPrincipal.add(jMenuSair);

        jMenuMinhaConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/gear20x20.png"))); // NOI18N
        jMenuMinhaConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuMinhaContaMouseClicked(evt);
            }
        });
        jMenuMinhaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMinhaContaActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(jMenuMinhaConta);

        setJMenuBar(jMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelImagemLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCarrinho)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImagemLogo)
                    .addComponent(jButtonCarrinho))
                .addGap(18, 18, 18)
                .addComponent(jPanelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarFuncionarioActionPerformed
        // TODO add your handling code here:
        JPanel jPanelCadastroFuncionario = new JPanelCadastroFuncionario();
        jPanelFundo.add(jPanelCadastroFuncionario);
        card.next(jPanelFundo);
    }//GEN-LAST:event_jMenuCadastrarFuncionarioActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        // TODO add your handling code here:

        int n = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Confirmar Opção",
                JOptionPane.YES_NO_OPTION);

        if (n == JOptionPane.YES_OPTION) {
            new JFrameTelaLogin();
            this.dispose();
        }
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jMenuCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarClienteActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jMenuCadastrarClienteActionPerformed

    private void jMenuConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultarClienteActionPerformed
        // TODO add your handling code here:
        JPanel jPanelConsultaCliente = new JPanelConsultaCliente();
        jPanelFundo.add(jPanelConsultaCliente);
        card.next(jPanelFundo);
        //card.next(jPanelConsultaCliente);
    }//GEN-LAST:event_jMenuConsultarClienteActionPerformed

    private void jMenuConsultarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultarFuncionarioActionPerformed
        // TODO add your handling code here:
        JPanel jPanelListaFuncionario = new JPanelListaFuncionario();
        jPanelFundo.add(jPanelListaFuncionario);
        card.next(jPanelFundo);
    }//GEN-LAST:event_jMenuConsultarFuncionarioActionPerformed

    private void jMenuCadastrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarVendaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuCadastrarVendaActionPerformed

    private void jMenuCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarProdutoActionPerformed
        // TODO add your handling code here:
        JPanel jPanelCadastrarProduto = new JPanelCadastrarProduto();
        jPanelFundo.add(jPanelCadastrarProduto);
        card.next(jPanelFundo);
    }//GEN-LAST:event_jMenuCadastrarProdutoActionPerformed

    private void jMenuConsultarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultarProdutoActionPerformed
        // TODO add your handling code here:
        ControlaVenda controlaVenda = new ControlaVenda();
        controlaVenda.getVendaAbertaFuncionario(funcionario);
        JPanel jPanelConsultarProduto = new JPanelConsultarProduto(controlaVenda.getVendaAbertaFuncionario(funcionario), funcionario);
        jPanelFundo.add(jPanelConsultarProduto);
        card.next(jPanelFundo);
    }//GEN-LAST:event_jMenuConsultarProdutoActionPerformed

    private void jMenuMinhaContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuMinhaContaMouseClicked
        // TODO add your handling code here:
        JPanel jPanelMinhaConta = new JPanelMinhaConta(funcionario);
        jPanelFundo.add(jPanelMinhaConta);
        card.next(jPanelFundo);
    }//GEN-LAST:event_jMenuMinhaContaMouseClicked

    private void jMenuMinhaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMinhaContaActionPerformed

    }//GEN-LAST:event_jMenuMinhaContaActionPerformed

    private void jMenuItemPedidosRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPedidosRepActionPerformed
        JPanel jPanelListaPedRep = new JPanelListaDePedidosDeReposicao();
        jPanelFundo.add(jPanelListaPedRep);
        card.next(jPanelFundo);
    }//GEN-LAST:event_jMenuItemPedidosRepActionPerformed

    private void jMenuItemNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovoPedidoActionPerformed
        JPanel jPanelNovoPedRep = new JPanelPedidoReposicaoEstoque();
        jPanelFundo.add(jPanelNovoPedRep);
        card.next(jPanelFundo);
    }//GEN-LAST:event_jMenuItemNovoPedidoActionPerformed

    private void jButtonCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarrinhoActionPerformed
        // TODO add your handling code here:
        ControlaVenda controlaVenda = new ControlaVenda();

        Date data = new Date();
        String idVenda;
        if (controlaVenda.getVendaAbertaFuncionario(funcionario) == null) {
            idVenda = funcionario.getIdFunc() + data.getTime();
            controlaVenda.novaVendaAberta(idVenda, funcionario);
            JPanel jPanelCarrinhoDeCompras = new JPanelCarrinhoDeCompras(funcionario, idVenda);
            jPanelFundo.add(jPanelCarrinhoDeCompras);
            card.next(jPanelFundo);
        } else {
            int n = JOptionPane.showConfirmDialog(
                    null,
                    "Já existem produtos no carrinho, gostaria de esvaziá-lo?",
                    "Confirmar Opção",
                    JOptionPane.YES_NO_OPTION);
            JPanel jPanelCarrinhoDeCompras;
            if (n == JOptionPane.YES_OPTION) {
                controlaVenda.excluiVendaAberta(funcionario);
                idVenda = funcionario.getIdFunc() + data.getTime();
                controlaVenda.novaVendaAberta(idVenda, funcionario);
                jPanelCarrinhoDeCompras = new JPanelCarrinhoDeCompras(funcionario, idVenda);
            } else {

                jPanelCarrinhoDeCompras = new JPanelCarrinhoDeCompras(funcionario, controlaVenda.getVendaAbertaFuncionario(funcionario).getVendaId());
            }

            jPanelFundo.add(jPanelCarrinhoDeCompras);
            card.next(jPanelFundo);
        }

    }//GEN-LAST:event_jButtonCarrinhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTelaGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCarrinho;
    private javax.swing.JLabel jLabelImagemLogo;
    private javax.swing.JMenuItem jMenuCadastrarCliente;
    private javax.swing.JMenuItem jMenuCadastrarFuncionario;
    private javax.swing.JMenuItem jMenuCadastrarProduto;
    private javax.swing.JMenuItem jMenuCadastrarVenda;
    private javax.swing.JMenu jMenuCaixa;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenuItem jMenuConsultarCaixa;
    private javax.swing.JMenuItem jMenuConsultarCliente;
    private javax.swing.JMenuItem jMenuConsultarFuncionario;
    private javax.swing.JMenuItem jMenuConsultarProduto;
    private javax.swing.JMenu jMenuFuncionario;
    private javax.swing.JMenuItem jMenuItemNovoPedido;
    private javax.swing.JMenuItem jMenuItemPedidosRep;
    private javax.swing.JMenu jMenuMinhaConta;
    private javax.swing.JMenu jMenuPedido;
    private javax.swing.JMenuBar jMenuPrincipal;
    private javax.swing.JMenu jMenuProduto;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuVenda;
    private javax.swing.JPanel jPanelFundo;
    // End of variables declaration//GEN-END:variables

    private void title(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
