/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControleEstoque;

import ControleProduto.ControlaProduto;
import ControleProduto.Produto;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafael
 */
public class JFrameConfirmarPedido extends javax.swing.JFrame {

    private ArrayList <ProdPedEstoque> prodpedes;
    private ArrayList <Produto> produtos;
    private PedidoEstoque pedido;
    JPanelListaDePedidosDeReposicao panelpai;
    
    /**
     * Creates new form JFrameConfirmarPedido
     */
    public JFrameConfirmarPedido() {
        initComponents();
    }

    public JFrameConfirmarPedido(PedidoEstoque pedido, JPanelListaDePedidosDeReposicao panelpai, boolean editavel)
    {
        initComponents();
        this.pedido = pedido;
        this.panelpai = panelpai;
        fetchListaProduto();
        updateListaProduto();
        
        if(editavel == false)
        {
            this.jButton1.setEnabled(false);
            this.jButton2.setEnabled(false);
            this.jTextField1.setEnabled(false);
            this.jLabel1.setEnabled(false);
            this.jButton1.setVisible(false);
            this.jButton2.setVisible(false);
            this.jTextField1.setVisible(false);
            this.jLabel1.setVisible(false);
            this.jButton3.setText("Voltar");
        }
    }
    
    public void fetchListaProduto()
    {
        produtos = new ControlaProduto().getListaProdutos();
        prodpedes = new ControlaProdPedEstoque().getListaProdPedEstoque(pedido);   
    }
    
    public void updateListaProduto()
    {        
        DefaultTableModel model = new DefaultTableModel();
        String[] colunas = new String[3];
        
        model.setColumnCount(3);
        colunas[0] = "Produto";
        colunas[1] = "Quantidade solicitada";
        colunas[2] = "Quantidade atendida";

        model.setColumnIdentifiers(colunas);
        
        for(ProdPedEstoque ppe : prodpedes)
        {
            Object[] obe = new Object[3];
            
            for(Produto p : produtos)
                if(ppe.getProduto().getProdId().contentEquals(p.getProdId()))
                    obe[0] = p.getNomeProd();
            
            obe[1] = ppe.getQuantidade();
            obe[2] = ppe.getQuantidadePedAtend();
            
            model.addRow(obe);
        }
        
        this.jTable1.setModel(model);
        this.jTable1.setFocusable(false);
        this.jTable1.setRowSelectionAllowed(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aplicar Alterações");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Quantidade:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(479, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)
                        .addComponent(jButton2))
                    .addComponent(jLabel1))
                .addGap(27, 27, 27))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(179, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(19, 19, 19))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        for(ProdPedEstoque ppe : prodpedes)
        {
            if(ppe.getQuantidade() == ppe.getQuantidadePedAtend())
                ppe.setStat(1); //Atendido totalmente
            else if(ppe.getQuantidadePedAtend() > 0 && ppe.getQuantidadePedAtend()< ppe.getQuantidade())
                ppe.setStat(2); //Parcialmente atendido
            else
                ppe.setStat(3); //Cancelado
        }
        
        Date datahoje = new Date();
        pedido.setDataAtend(datahoje);
        boolean persistiu = new ControlaPedidoEstoque().persistePedidoEstoque(pedido);
        boolean erro_cadastro = !persistiu;       
        
        for(ProdPedEstoque ppe : prodpedes)
        {
            persistiu = new ControlaProdPedEstoque().persisteProdPedEstoque(ppe);
            if(!persistiu)
            {
                erro_cadastro = true;
            }
        }
        
        if(!erro_cadastro){
            JOptionPane.showMessageDialog(null, "Pedido Confirmado com Sucesso!");
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao salvar alterações!");
        }
        
        panelpai.updatePedidosEstoque();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jTable1.getSelectedRow() == -1)
            return;
        
        int quantidade_atendida = Integer.parseInt(jTextField1.getText());
        int quantidade_demandada = prodpedes.get(jTable1.getSelectedRow()).getQuantidade();
        
        if(quantidade_atendida <= quantidade_demandada && quantidade_atendida > 0)
            prodpedes.get(jTable1.getSelectedRow()).setQuantidadePedAtend(quantidade_atendida);
        else
            JOptionPane.showMessageDialog(null, "Digite um valor válido!");
        
        updateListaProduto();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameConfirmarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameConfirmarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameConfirmarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameConfirmarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameConfirmarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
