/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControleDeVendas;

import ControleCliente.Cliente;
import ControleCliente.ControlaCliente;
import ControleNotaFiscal.ControleNotaFiscal;
import ControleProduto.ControlaProduto;
import ControleProduto.Produto;
import ControleDeVendas.ProdVenda;
import GerenciamentoDeFuncionarios.ControlaFuncionario;
import GerenciamentoDeFuncionarios.Funcionario;
import Relatorios.JFrameNotaFiscal;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import org.hibernate.Hibernate;

/**
 *
 * @author admin
 */
public class JPanelVendasFinalizadas extends javax.swing.JPanel {

    /**
     * Creates new form JPanelVendasFinalizadas
     */
    
    DefaultTableModel modelo;
    ArrayList<VendaFinalizada> vendas;
    Funcionario func;
    Cliente cli;
    VendaFinalizada venda;
    ProdVenda prodVenda;
    ArrayList<ProdVenda> prodsVenda;
    DefaultTableModel tableModel;
    
    public JPanelVendasFinalizadas() {
        initComponents();
        jInternalFrameConsultaVendaFinalizada.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameConsultaVendaFinalizada = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProdsVenda = new javax.swing.JTable();
        jLabelIDVenda = new javax.swing.JLabel();
        jLabelNomeFunc = new javax.swing.JLabel();
        jLabelNomeCli = new javax.swing.JLabel();
        jLabelDataVenda = new javax.swing.JLabel();
        jLabelFormaPagto = new javax.swing.JLabel();
        jLabelQuantidadeParcelas = new javax.swing.JLabel();
        jLabelIDFuncionario = new javax.swing.JLabel();
        jLabelIDCliente = new javax.swing.JLabel();
        jLabelValorTotal = new javax.swing.JLabel();
        jButtonFecharInternal = new javax.swing.JButton();
        jTextFieldIDVenda = new javax.swing.JTextField();
        jTextFieldNomeFunc = new javax.swing.JTextField();
        jTextFieldNomeCli = new javax.swing.JTextField();
        jTextFieldDataVenda = new javax.swing.JTextField();
        jTextFieldFormaPagamento = new javax.swing.JTextField();
        jTextFieldQuantidadeParcelas = new javax.swing.JTextField();
        jTextFieldValorTotal = new javax.swing.JTextField();
        jTextFieldIDCliente = new javax.swing.JTextField();
        jTextFieldIDFuncionario = new javax.swing.JTextField();
        jButtonGerarNotaFiscal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVendasFinalizadas = new javax.swing.JTable();
        jComboBoxFiltroPesquisa = new javax.swing.JComboBox<String>();
        jButtonPesquisar = new javax.swing.JButton();
        jTextFieldCampoPesquisa = new javax.swing.JTextField();
        jButtonConsultar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrameConsultaVendaFinalizada.setVisible(true);

        jTableProdsVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Valor Unitário", "Quantidade", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProdsVenda.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableProdsVenda);

        jLabelIDVenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelIDVenda.setText("ID da Venda");

        jLabelNomeFunc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNomeFunc.setText("Nome do Funcionario");

        jLabelNomeCli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNomeCli.setText("Nome do Cliente");

        jLabelDataVenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDataVenda.setText("Data da Venda");

        jLabelFormaPagto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelFormaPagto.setText("Forma de Pagamento");

        jLabelQuantidadeParcelas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelQuantidadeParcelas.setText("Quantidade de Parcelas");

        jLabelIDFuncionario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelIDFuncionario.setText("ID do Funcionário");

        jLabelIDCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelIDCliente.setText("ID do Cliente");

        jLabelValorTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelValorTotal.setText("Valor Total");

        jButtonFecharInternal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonFecharInternal.setText("Fechar");
        jButtonFecharInternal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharInternalActionPerformed(evt);
            }
        });

        jTextFieldIDVenda.setEditable(false);
        jTextFieldIDVenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldIDVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDVendaActionPerformed(evt);
            }
        });

        jTextFieldNomeFunc.setEditable(false);
        jTextFieldNomeFunc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldNomeCli.setEditable(false);
        jTextFieldNomeCli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldDataVenda.setEditable(false);
        jTextFieldDataVenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldFormaPagamento.setEditable(false);
        jTextFieldFormaPagamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldQuantidadeParcelas.setEditable(false);
        jTextFieldQuantidadeParcelas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldValorTotal.setEditable(false);
        jTextFieldValorTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldIDCliente.setEditable(false);
        jTextFieldIDCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldIDFuncionario.setEditable(false);
        jTextFieldIDFuncionario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButtonGerarNotaFiscal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonGerarNotaFiscal.setText("Gerar Nota Fiscal");
        jButtonGerarNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarNotaFiscalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameConsultaVendaFinalizadaLayout = new javax.swing.GroupLayout(jInternalFrameConsultaVendaFinalizada.getContentPane());
        jInternalFrameConsultaVendaFinalizada.getContentPane().setLayout(jInternalFrameConsultaVendaFinalizadaLayout);
        jInternalFrameConsultaVendaFinalizadaLayout.setHorizontalGroup(
            jInternalFrameConsultaVendaFinalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createSequentialGroup()
                .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrameConsultaVendaFinalizadaLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createSequentialGroup()
                        .addContainerGap(51, Short.MAX_VALUE)
                        .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createSequentialGroup()
                                .addComponent(jButtonGerarNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)
                                .addComponent(jButtonFecharInternal))
                            .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createSequentialGroup()
                                .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelIDVenda)
                                    .addComponent(jLabelFormaPagto)
                                    .addComponent(jLabelDataVenda)
                                    .addComponent(jLabelNomeCli)
                                    .addComponent(jLabelNomeFunc))
                                .addGap(18, 18, 18)
                                .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createSequentialGroup()
                                        .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldFormaPagamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                                            .addComponent(jTextFieldDataVenda)
                                            .addComponent(jTextFieldNomeCli)
                                            .addComponent(jTextFieldNomeFunc))
                                        .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabelIDFuncionario))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameConsultaVendaFinalizadaLayout.createSequentialGroup()
                                                        .addGap(40, 40, 40)
                                                        .addComponent(jLabelIDCliente)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameConsultaVendaFinalizadaLayout.createSequentialGroup()
                                                    .addGap(51, 51, 51)
                                                    .addComponent(jLabelValorTotal)))
                                            .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelQuantidadeParcelas)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                            .addComponent(jTextFieldIDCliente)
                                            .addComponent(jTextFieldIDFuncionario)
                                            .addComponent(jTextFieldQuantidadeParcelas)))
                                    .addComponent(jTextFieldIDVenda))))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jInternalFrameConsultaVendaFinalizadaLayout.setVerticalGroup(
            jInternalFrameConsultaVendaFinalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameConsultaVendaFinalizadaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIDVenda)
                    .addComponent(jTextFieldIDVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeFunc)
                    .addComponent(jLabelIDFuncionario)
                    .addComponent(jTextFieldNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIDFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeCli)
                    .addComponent(jLabelIDCliente)
                    .addComponent(jTextFieldNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataVenda)
                    .addComponent(jLabelValorTotal)
                    .addComponent(jTextFieldDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFormaPagto)
                            .addComponent(jTextFieldFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldQuantidadeParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelQuantidadeParcelas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameConsultaVendaFinalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFecharInternal)
                    .addComponent(jButtonGerarNotaFiscal))
                .addContainerGap())
        );

        add(jInternalFrameConsultaVendaFinalizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 930, 540));

        jTableVendasFinalizadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Data da Venda", "Cliente", "Funcionario", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVendasFinalizadas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableVendasFinalizadas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 81, 941, -1));

        jComboBoxFiltroPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxFiltroPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome do Cliente", "Nome do Funcionário", "ID" }));
        jComboBoxFiltroPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFiltroPesquisaActionPerformed(evt);
            }
        });
        add(jComboBoxFiltroPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 29, 150, 34));

        jButtonPesquisar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        add(jButtonPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 29, 90, 34));

        jTextFieldCampoPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldCampoPesquisa.setText("Pesquisar Venda");
        add(jTextFieldCampoPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 29, 685, 34));

        jButtonConsultar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });
        add(jButtonConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 534, 121, 31));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:
        switch (jComboBoxFiltroPesquisa.getSelectedIndex()) {
            case 0:
                if (jTextFieldCampoPesquisa.getText().equals("Pesquisar venda")) {
                    JOptionPane.showMessageDialog(null, "Digite o nome do cliente para a busca.");
                } else {
                    modelo = (DefaultTableModel) jTableVendasFinalizadas.getModel();
                    modelo.setNumRows(0);
                    vendas = new ControlaVenda().getListaVendasFinalizadas();
                    for (VendaFinalizada v : vendas) {
                        Hibernate.initialize(v.getCliente().getCliId());
                        cli = new ControlaCliente().getCliente(v.getCliente().getCliId());
                        if (cli.getNome().startsWith(jTextFieldCampoPesquisa.getText())) {
                            Hibernate.initialize(v.getFuncionario().getIdFunc());
                            func = new ControlaFuncionario().getFuncionario(v.getFuncionario().getIdFunc());
                            modelo.addRow(new Object[]{v.getVendaId(), v.getDataCompra(), cli.getNome(), func.getNome(), v.getValorTotal()});
                        }
                    }
                }
                break;

            case 1:
                if (jTextFieldCampoPesquisa.getText().equals("Pesquisar venda")) {
                    JOptionPane.showMessageDialog(null, "Digite o nome do funcionario para a busca.");
                } else {
                    modelo = (DefaultTableModel) jTableVendasFinalizadas.getModel();
                    modelo.setNumRows(0);
                    vendas = new ControlaVenda().getListaVendasFinalizadas();
                    for (VendaFinalizada v : vendas) {
                        Hibernate.initialize(v.getFuncionario().getIdFunc());
                        func = new ControlaFuncionario().getFuncionario(v.getFuncionario().getIdFunc());
                        if (func.getNome().startsWith(jTextFieldCampoPesquisa.getText())) {
                            Hibernate.initialize(v.getCliente().getCliId());
                            cli = new ControlaCliente().getCliente(v.getCliente().getCliId());
                            modelo.addRow(new Object[]{v.getVendaId(), v.getDataCompra(), cli.getNome(), func.getNome(), v.getValorTotal()});
                        }
                    }
                }
                break;
            case 2:
                if (jTextFieldCampoPesquisa.getText().equals("Pesquisar venda")) {
                    JOptionPane.showMessageDialog(null, "Digite o ID da venda para começar a busca.");
                } else {
                    modelo = (DefaultTableModel) jTableVendasFinalizadas.getModel();
                    modelo.setNumRows(0);
                    vendas = new ControlaVenda().getListaVendasFinalizadas();
                    for (VendaFinalizada v : vendas) {
                        if (v.getVendaId().startsWith(jTextFieldCampoPesquisa.getText())) {
                            Hibernate.initialize(v.getFuncionario().getIdFunc());
                            func = new ControlaFuncionario().getFuncionario(v.getFuncionario().getIdFunc());
                            Hibernate.initialize(v.getCliente().getCliId());
                            cli = new ControlaCliente().getCliente(v.getCliente().getCliId());
                            modelo.addRow(new Object[]{v.getVendaId(), v.getDataCompra(), cli.getNome(), func.getNome(), v.getValorTotal()});
                        }
                    }
                }
                break;
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jComboBoxFiltroPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltroPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFiltroPesquisaActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        // TODO add your handling code here:
        jButtonConsultar.setVisible(false);
        int indiceProd = jTableVendasFinalizadas.getSelectedRow();
        if (indiceProd == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma venda para ter os detalhes.");
        } else {
            venda = new ControlaVenda().vendaToVendaFinalizada(new ControlaVenda().getVenda((String) jTableVendasFinalizadas.getValueAt(indiceProd, 0)));
            
            jTextFieldIDVenda.setText(venda.getVendaId());
            jTextFieldIDFuncionario.setText(func.getIdFunc());
            jTextFieldNomeFunc.setText(func.getNome());
            jTextFieldIDCliente.setText(cli.getCliId());
            jTextFieldNomeCli.setText(cli.getNome() + " " + cli.getSobrenome());
            jTextFieldDataVenda.setText(venda.getDataCompra().toString());
            jTextFieldFormaPagamento.setText(venda.getFormaPagamento());
            jTextFieldQuantidadeParcelas.setText(venda.getNumParcelas().toString());
            jTextFieldValorTotal.setText(venda.getValorTotal().toString());
            jInternalFrameConsultaVendaFinalizada.setVisible(true);
            
            tableModel = (DefaultTableModel) jTableProdsVenda.getModel();
            tableModel.setNumRows(0);
            prodsVenda = new ControlaProdVenda().getProdsVenda(venda.getVendaId());
            ControlaProduto controlaProduto = new ControlaProduto();
            Produto produto;

            for (ProdVenda pv : prodsVenda) {
                Hibernate.initialize(pv.getProduto().getProdId());
                produto = controlaProduto.getProduto(pv.getProduto().getProdId());
                tableModel.addRow(new Object[]{produto.getProdId(), produto.getNomeProd(), pv.getValorUnitario(), pv.getQuantidade(), "" + (pv.getQuantidade() * pv.getValorUnitario()), false});
            }
            System.out.println();

        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonFecharInternalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharInternalActionPerformed
        // TODO add your handling code here:
        jInternalFrameConsultaVendaFinalizada.setVisible(false);
        jButtonConsultar.setVisible(true);
    }//GEN-LAST:event_jButtonFecharInternalActionPerformed

    private void jButtonGerarNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarNotaFiscalActionPerformed
         JFrameNotaFiscal notaFiscal = new JFrameNotaFiscal( cli, func, venda);

    }//GEN-LAST:event_jButtonGerarNotaFiscalActionPerformed

    private void jTextFieldIDVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDVendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonFecharInternal;
    private javax.swing.JButton jButtonGerarNotaFiscal;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JComboBox<String> jComboBoxFiltroPesquisa;
    private javax.swing.JInternalFrame jInternalFrameConsultaVendaFinalizada;
    private javax.swing.JLabel jLabelDataVenda;
    private javax.swing.JLabel jLabelFormaPagto;
    private javax.swing.JLabel jLabelIDCliente;
    private javax.swing.JLabel jLabelIDFuncionario;
    private javax.swing.JLabel jLabelIDVenda;
    private javax.swing.JLabel jLabelNomeCli;
    private javax.swing.JLabel jLabelNomeFunc;
    private javax.swing.JLabel jLabelQuantidadeParcelas;
    private javax.swing.JLabel jLabelValorTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProdsVenda;
    private javax.swing.JTable jTableVendasFinalizadas;
    private javax.swing.JTextField jTextFieldCampoPesquisa;
    private javax.swing.JTextField jTextFieldDataVenda;
    private javax.swing.JTextField jTextFieldFormaPagamento;
    private javax.swing.JTextField jTextFieldIDCliente;
    private javax.swing.JTextField jTextFieldIDFuncionario;
    private javax.swing.JTextField jTextFieldIDVenda;
    private javax.swing.JTextField jTextFieldNomeCli;
    private javax.swing.JTextField jTextFieldNomeFunc;
    private javax.swing.JTextField jTextFieldQuantidadeParcelas;
    private javax.swing.JTextField jTextFieldValorTotal;
    // End of variables declaration//GEN-END:variables
}
